// Generated by Copilot
// Komponent do wyświet          <div className="price-display">
// Generated by Copilot
// Komponent do wyświetlania szczegółowych informacji o filmie
// Powinien formatować datę wydania w polskim formacie
// Powinien formatować cenę jako walutę polską
// Powinien obsłużyć przypadek gdy movie jest null/undefined
import React from 'react';
import { MovieDetailProps } from '@/types/Movie';
import { 
  formatCurrency, 
  formatDateLong, 
  formatDateShort, 
  calculateMovieAge, 
  getPriceCategory,
  isNewMovie
} from '@/utils/formatters';
import './MovieDetail.css';

const MovieDetail: React.FC<MovieDetailProps> = ({ movie }) => {
  // Obsługa przypadku gdy film nie istnieje
  if (!movie) {
    return (
      <div className="movie-detail-empty">
        <div className="empty-state">
          <h2>🎬 Brak wybranego filmu</h2>
          <p>Wybierz film z listy, aby zobaczyć szczegółowe informacje.</p>
        </div>
      </div>
    );
  }

  // Sprawdzenie czy film jest nowy
  const isNew = isNewMovie(movie.releaseDate);
  const priceCategory = getPriceCategory(movie.ticketPrice);
  const movieAge = calculateMovieAge(movie.releaseDate);

  return (
    <div className="movie-detail">
      <div className="movie-detail-container">
        {/* Header Section */}
        <header className="movie-detail-header">
          <div className="movie-title-section">
            <h1 className="movie-title">
              {movie.title}
              {isNew && <span className="new-badge">NOWOŚĆ!</span>}
            </h1>
            <div className="movie-subtitle">
              <span className="movie-id">Film ID: {movie.id}</span>
            </div>
          </div>
          <div className="movie-price-section">
            <div className="price-display">
              <span className="price-amount">{formatCurrency(movie.ticketPrice)}</span>
              <span className={`price-category ${priceCategory.className}`}>
                {priceCategory.label}
              </span>
            </div>
          </div>
        </header>

        {/* Main Content */}
        <main className="movie-detail-content">
          <div className="detail-grid">
            {/* Director Information */}
            <div className="detail-card">
              <div className="detail-icon">🎬</div>
              <div className="detail-info">
                <h3>Reżyser</h3>
                <p className="detail-value">{movie.director}</p>
              </div>
            </div>

            {/* Release Date Information */}
            <div className="detail-card">
              <div className="detail-icon">📅</div>
              <div className="detail-info">
                <h3>Data premiery</h3>
                <p className="detail-value">{formatDateLong(movie.releaseDate)}</p>
                <p className="detail-subvalue">{formatDateShort(movie.releaseDate)}</p>
              </div>
            </div>

            {/* Movie Age */}
            <div className="detail-card">
              <div className="detail-icon">⏰</div>
              <div className="detail-info">
                <h3>Od premiery</h3>
                <p className="detail-value">{movieAge}</p>
              </div>
            </div>

            {/* Ticket Price Details */}
            <div className="detail-card">
              <div className="detail-icon">🎟️</div>
              <div className="detail-info">
                <h3>Cena biletu</h3>
                <p className="detail-value">{formatCurrency(movie.ticketPrice)}</p>
                <p className="detail-subvalue">Kategoria: {priceCategory.label}</p>
                <p className="detail-subvalue">{priceCategory.description}</p>
              </div>
            </div>
          </div>

          {/* Additional Information */}
          <div className="movie-meta">
            <div className="meta-section">
              <h3>📊 Informacje szczegółowe</h3>
              <div className="meta-grid">
                <div className="meta-item">
                  <span className="meta-label">Identyfikator:</span>
                  <span className="meta-value">{movie.id}</span>
                </div>
                <div className="meta-item">
                  <span className="meta-label">Tytuł:</span>
                  <span className="meta-value">{movie.title}</span>
                </div>
                <div className="meta-item">
                  <span className="meta-label">Reżyser:</span>
                  <span className="meta-value">{movie.director}</span>
                </div>
                <div className="meta-item">
                  <span className="meta-label">Data wydania:</span>
                  <span className="meta-value">{movie.releaseDate}</span>
                </div>
                <div className="meta-item">
                  <span className="meta-label">Cena (PLN):</span>
                  <span className="meta-value">{movie.ticketPrice.toFixed(2)}</span>
                </div>
                <div className="meta-item">
                  <span className="meta-label">Status:</span>
                  <span className="meta-value">{isNew ? 'Nowość' : 'Dostępny'}</span>
                </div>
              </div>
            </div>
          </div>
        </main>
      </div>
    </div>
  );
};

export default MovieDetail;