// Generated by Copilot
// Formularz React do dodawania nowego filmu
// Powinien zawierać pola: title, director, ticketPrice, releaseDate
// Powinien validować wszystkie pola przed submitem
// Powinien używać useState do zarządzania stanem formularza
// Powinien wywołać callback onSubmit z danymi filmu
import { useState } from 'react';
import { CreateMovieData } from '@/types/Movie';
import './AddMovieForm.css';

interface AddMovieFormProps {
  onSubmit: (movieData: CreateMovieData) => Promise<void>;
  onCancel?: () => void;
  isLoading?: boolean;
}

interface FormErrors {
  title?: string;
  director?: string;
  ticketPrice?: string;
  releaseDate?: string;
}

export const AddMovieForm: React.FC<AddMovieFormProps> = ({
  onSubmit,
  onCancel,
  isLoading = false
}) => {
  // Formularz React z kontrolowanymi komponentami
  const [formData, setFormData] = useState<CreateMovieData>({
    title: '',
    director: '',
    ticketPrice: 0,
    releaseDate: ''
  });

  const [errors, setErrors] = useState<FormErrors>({});
  const [isSubmitting, setIsSubmitting] = useState(false);

  // Walidacja formularza przed submitem
  const validateForm = (): boolean => {
    const newErrors: FormErrors = {};

    // Walidacja tytułu
    if (!formData.title.trim()) {
      newErrors.title = 'Tytuł filmu jest wymagany';
    } else if (formData.title.trim().length < 2) {
      newErrors.title = 'Tytuł musi mieć co najmniej 2 znaki';
    }

    // Walidacja reżysera
    if (!formData.director.trim()) {
      newErrors.director = 'Reżyser jest wymagany';
    } else if (formData.director.trim().length < 2) {
      newErrors.director = 'Imię reżysera musi mieć co najmniej 2 znaki';
    }

    // Walidacja ceny
    if (formData.ticketPrice <= 0) {
      newErrors.ticketPrice = 'Cena musi być większa od 0';
    } else if (formData.ticketPrice > 1000) {
      newErrors.ticketPrice = 'Cena nie może przekraczać 1000 PLN';
    }

    // Walidacja daty wydania
    if (!formData.releaseDate) {
      newErrors.releaseDate = 'Data wydania jest wymagana';
    } else {
      const selectedDate = new Date(formData.releaseDate);
      const today = new Date();
      const minDate = new Date('1900-01-01');
      
      if (selectedDate > today) {
        newErrors.releaseDate = 'Data wydania nie może być z przyszłości';
      } else if (selectedDate < minDate) {
        newErrors.releaseDate = 'Data wydania nie może być wcześniejsza niż 1900 rok';
      }
    }

    setErrors(newErrors);
    return Object.keys(newErrors).length === 0;
  };

  // Obsługa zmiany wartości w polach formularza
  const handleInputChange = (field: keyof CreateMovieData, value: string | number) => {
    setFormData(prev => ({
      ...prev,
      [field]: value
    }));

    // Usunięcie błędu dla tego pola po zmianie wartości
    if (errors[field]) {
      setErrors(prev => ({
        ...prev,
        [field]: undefined
      }));
    }
  };

  // Obsługa submitu formularza
  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    
    if (!validateForm()) {
      return;
    }

    setIsSubmitting(true);
    
    try {
      await onSubmit(formData);
      // Reset formularza po udanym dodaniu
      handleReset();
    } catch (error) {
      console.error('Błąd podczas dodawania filmu:', error);
    } finally {
      setIsSubmitting(false);
    }
  };

  // Reset formularza
  const handleReset = () => {
    setFormData({
      title: '',
      director: '',
      ticketPrice: 0,
      releaseDate: ''
    });
    setErrors({});
  };

  const isFormDisabled = isLoading || isSubmitting;

  return (
    <div className="add-movie-form-container">
      <form className="add-movie-form" onSubmit={handleSubmit}>
        <header className="form-header">
          <h2>🎬 Dodaj nowy film</h2>
          <p>Wypełnij wszystkie pola, aby dodać film do kolekcji</p>
        </header>

        <div className="form-fields">
          {/* Pole tytułu */}
          <div className="form-field">
            <label htmlFor="title">
              Tytuł filmu <span className="required">*</span>
            </label>
            <input
              id="title"
              type="text"
              value={formData.title}
              onChange={(e) => handleInputChange('title', e.target.value)}
              className={errors.title ? 'error' : ''}
              placeholder="np. Król Lew"
              disabled={isFormDisabled}
              maxLength={100}
            />
            {errors.title && <span className="error-message">{errors.title}</span>}
          </div>

          {/* Pole reżysera */}
          <div className="form-field">
            <label htmlFor="director">
              Reżyser <span className="required">*</span>
            </label>
            <input
              id="director"
              type="text"
              value={formData.director}
              onChange={(e) => handleInputChange('director', e.target.value)}
              className={errors.director ? 'error' : ''}
              placeholder="np. Steven Spielberg"
              disabled={isFormDisabled}
              maxLength={50}
            />
            {errors.director && <span className="error-message">{errors.director}</span>}
          </div>

          {/* Pole ceny biletu */}
          <div className="form-field">
            <label htmlFor="ticketPrice">
              Cena biletu (PLN) <span className="required">*</span>
            </label>
            <input
              id="ticketPrice"
              type="number"
              value={formData.ticketPrice || ''}
              onChange={(e) => handleInputChange('ticketPrice', parseFloat(e.target.value) || 0)}
              className={errors.ticketPrice ? 'error' : ''}
              placeholder="25.99"
              disabled={isFormDisabled}
              min="0.01"
              max="1000"
              step="0.01"
            />
            {errors.ticketPrice && <span className="error-message">{errors.ticketPrice}</span>}
          </div>

          {/* Pole daty wydania */}
          <div className="form-field">
            <label htmlFor="releaseDate">
              Data wydania <span className="required">*</span>
            </label>
            <input
              id="releaseDate"
              type="date"
              value={formData.releaseDate}
              onChange={(e) => handleInputChange('releaseDate', e.target.value)}
              className={errors.releaseDate ? 'error' : ''}
              disabled={isFormDisabled}
              min="1900-01-01"
              max={new Date().toISOString().split('T')[0]}
            />
            {errors.releaseDate && <span className="error-message">{errors.releaseDate}</span>}
          </div>
        </div>

        <div className="form-actions">
          <button
            type="button"
            onClick={handleReset}
            className="reset-button"
            disabled={isFormDisabled}
          >
            🔄 Wyczyść formularz
          </button>
          
          {onCancel && (
            <button
              type="button"
              onClick={onCancel}
              className="cancel-button"
              disabled={isFormDisabled}
            >
              ❌ Anuluj
            </button>
          )}
          
          <button
            type="submit"
            className="submit-button"
            disabled={isFormDisabled}
          >
            {isSubmitting ? '⏳ Dodawanie...' : '✅ Dodaj film'}
          </button>
        </div>
      </form>
    </div>
  );
};