// Generated by Copilot
// Main App component for Module 1: React Basics
// Podstawowy komponent aplikacji do zarządzania filmami
import { useState } from 'react';
import { Movie, CreateMovieData } from '@/types/Movie';
import { MovieList, MovieDetail, AddMovieForm, MovieSearch, SearchAndSortOptions } from '@/components';
import { useMovies } from '@/hooks';

function App() {
  // Stan wybranego filmu i widoku
  const [selectedMovie, setSelectedMovie] = useState<Movie | null>(null);
  const [currentView, setCurrentView] = useState<'list' | 'detail' | 'add'>('list');
  
  // Stan dla przefiltrowanych filmów
  const [filteredMovies, setFilteredMovies] = useState<Movie[]>([]);
  const [searchOptions, setSearchOptions] = useState<SearchAndSortOptions | null>(null);

  // Użycie custom hook do zarządzania filmami
  const { 
    movies, 
    loading, 
    error, 
    refreshMovies,
    addMovie 
  } = useMovies();

  // Funkcja obsługi kliknięcia w film
  const handleMovieClick = (movie: Movie) => {
    setSelectedMovie(movie);
    setCurrentView('detail');
  };

  // Funkcja powrotu do listy
  const handleBackToList = () => {
    setCurrentView('list');
    setSelectedMovie(null);
  };

  // Funkcja przejścia do formularza dodawania filmu
  const handleShowAddForm = () => {
    setCurrentView('add');
    setSelectedMovie(null);
  };

  // Funkcja obsługi dodawania nowego filmu
  const handleAddMovie = async (movieData: CreateMovieData) => {
    await addMovie(movieData);
    setCurrentView('list'); // Powrót do listy po dodaniu
  };

  // Funkcje obsługi wyszukiwania i filtrowania
  const handleFilteredMoviesChange = (filtered: Movie[]) => {
    setFilteredMovies(filtered);
  };

  const handleSearchOptionsChange = (options: SearchAndSortOptions) => {
    setSearchOptions(options);
  };

  // Określenie, które filmy wyświetlić
  const moviesToDisplay = filteredMovies.length > 0 || searchOptions?.searchQuery 
    ? filteredMovies 
    : movies;

  return (
    <div className="app">
      <header className="app-header">
        <h1>🎬 Movie Management App</h1>
        <p>Module 1: React Basics with GitHub Copilot</p>
        
        <nav className="app-navigation">
          {currentView === 'list' ? (
            <button 
              className="add-movie-button"
              onClick={handleShowAddForm}
              disabled={loading}
            >
              ➕ Dodaj nowy film
            </button>
          ) : (
            <button 
              className="back-button"
              onClick={handleBackToList}
            >
              ← Powrót do listy filmów
            </button>
          )}
        </nav>
      </header>
      
      <main className="app-main">
        {currentView === 'list' ? (
          <section className="movie-section">
            {loading ? (
              <div className="loading-state">
                <h2>⏳ Ładowanie filmów...</h2>
                <p>Proszę czekać, pobieramy dane o filmach.</p>
              </div>
            ) : error ? (
              <div className="error-state">
                <h2>❌ Wystąpił błąd</h2>
                <p>{error}</p>
                <button 
                  className="refresh-button"
                  onClick={refreshMovies}
                >
                  🔄 Spróbuj ponownie
                </button>
              </div>
            ) : (
              <>
                <MovieSearch
                  movies={movies}
                  onFilteredMoviesChange={handleFilteredMoviesChange}
                  onOptionsChange={handleSearchOptionsChange}
                />
                <MovieList 
                  movies={moviesToDisplay}
                  onMovieClick={handleMovieClick}
                />
              </>
            )}
          </section>
        ) : currentView === 'detail' ? (
          <section className="movie-detail-section">
            <MovieDetail movie={selectedMovie} />
          </section>
        ) : currentView === 'add' ? (
          <section className="add-movie-section">
            <AddMovieForm 
              onSubmit={handleAddMovie}
              onCancel={handleBackToList}
              isLoading={loading}
            />
          </section>
        ) : null}
      </main>
    </div>
  );
}

export default App;