// Generated by Copilot
// Main App component for Module 1: React Basics
// Podstawowy komponent aplikacji do zarządzania filmami
import { Movie } from '@/types/Movie';

function App() {
  // Mock data dla development
  const mockMovies: Movie[] = [
    {
      id: '1',
      title: 'Oppenheimer',
      director: 'Christopher Nolan',
      ticketPrice: 25.99,
      releaseDate: '2023-07-21'
    },
    {
      id: '2',
      title: 'Barbie',
      director: 'Greta Gerwig',
      ticketPrice: 22.50,
      releaseDate: '2023-07-21'
    },
    {
      id: '3',
      title: 'Dune: Part Two',
      director: 'Denis Villeneuve',
      ticketPrice: 28.00,
      releaseDate: '2024-03-01'
    }
  ];

  return (
    <div className="app">
      <header className="app-header">
        <h1>🎬 Movie Management App</h1>
        <p>Module 1: React Basics with GitHub Copilot</p>
      </header>
      
      <main className="app-main">
        <section className="movie-section">
          <h2>Available Movies ({mockMovies.length})</h2>
          <div className="movie-grid">
            {mockMovies.map(movie => (
              <div key={movie.id} className="movie-card">
                <h3>{movie.title}</h3>
                <p><strong>Director:</strong> {movie.director}</p>
                <p><strong>Price:</strong> {movie.ticketPrice.toFixed(2)} PLN</p>
                <p><strong>Release:</strong> {movie.releaseDate}</p>
              </div>
            ))}
          </div>
        </section>
        
        <section className="development-info">
          <h3>🚧 Development Status</h3>
          <ul>
            <li>✅ Phase 1: Project Structure</li>
            <li>✅ Phase 2: Core Types & Interfaces</li>
            <li>⏳ Phase 3: MovieList Component</li>
            <li>⏳ Phase 4: MovieDetail Component</li>
            <li>⏳ Phase 5: useMovies Hook</li>
            <li>⏳ Phase 6: AddMovieForm Component</li>
            <li>⏳ Phase 7: Search & Sort Features</li>
            <li>⏳ Phase 8: Final Integration</li>
          </ul>
        </section>
      </main>
    </div>
  );
}

export default App;