// Generated by Copilot
// Komponent karty filmu do wyświetlania podstawowych informacji
// Powinien wyświetlać tytuł, reżysera, cenę i datę wydania
// Powinien mieć atrakcyjny design z hover efektami
import React from 'react';
import { Movie } from '@/types/Movie';

interface MovieCardProps {
  movie: Movie;
  onClick?: (movie: Movie) => void;
}

const MovieCard: React.FC<MovieCardProps> = ({ movie, onClick }) => {
  // Formatowanie ceny w polskiej walucie
  const formatPrice = (price: number): string => {
    return new Intl.NumberFormat('pl-PL', {
      style: 'currency',
      currency: 'PLN'
    }).format(price);
  };

  // Formatowanie daty w polskim formacie
  const formatDate = (dateString: string): string => {
    const date = new Date(dateString);
    return date.toLocaleDateString('pl-PL', {
      year: 'numeric',
      month: 'long',
      day: 'numeric'
    });
  };

  const handleClick = () => {
    if (onClick) {
      onClick(movie);
    }
  };

  return (
    <div 
      className={`movie-card ${onClick ? 'clickable' : ''}`}
      onClick={handleClick}
    >
      <div className="movie-card-header">
        <h3 className="movie-title">{movie.title}</h3>
        <div className="movie-price">
          {formatPrice(movie.ticketPrice)}
        </div>
      </div>
      
      <div className="movie-card-content">
        <div className="movie-info">
          <span className="info-label">Reżyser:</span>
          <span className="info-value">{movie.director}</span>
        </div>
        
        <div className="movie-info">
          <span className="info-label">Data premiery:</span>
          <span className="info-value">{formatDate(movie.releaseDate)}</span>
        </div>
      </div>
      
      <div className="movie-card-footer">
        <div className="movie-id">ID: {movie.id}</div>
        {onClick && (
          <div className="click-hint">Kliknij aby zobaczyć szczegóły</div>
        )}
      </div>
    </div>
  );
};

export default MovieCard;