// Generated by Copilot
// Komponent React do wyświetlania listy filmów
// Powinien przyjmować tablicę obiektów Movie jako props
// Każdy film powinien być wyświetlony jako karta z tytułem, reżyserem i ceną
import React from 'react';
import { MovieListProps } from '@/types/Movie';
import MovieCard from './MovieCard';
import './MovieList.css';

const MovieList: React.FC<MovieListProps> = ({ movies, onMovieClick }) => {
  if (!movies || movies.length === 0) {
    return (
      <div className="movie-list-empty">
        <h3>Brak dostępnych filmów</h3>
        <p>Nie znaleziono żadnych filmów do wyświetlenia.</p>
      </div>
    );
  }

  return (
    <div className="movie-list">
      <div className="movie-list-header">
        <h2>Lista Filmów</h2>
        <span className="movie-count">
          Znaleziono: {movies.length} {movies.length === 1 ? 'film' : 'filmów'}
        </span>
      </div>
      
      <div className="movie-grid">
        {movies.map((movie) => (
          <MovieCard 
            key={movie.id} 
            movie={movie}
            onClick={onMovieClick}
          />
        ))}
      </div>
    </div>
  );
};

export default MovieList;